# Generated by Django 6.0.5 on 2026-08-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_usersetting_pooling_interval_alter_usersetting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='pooling_interval',
            field=models.IntegerField(default=2, null=True),
        ),
    ]
