# Generated by Django 6.0.5 on 2026-08-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_usersetting_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSetting',
        ),
    ]
