# Generated by Django 6.0.5 on 2026-05-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('description', models.TextField(max_length=255)),
                ('ports', models.JSONField(default=list)),
            ],
        ),
    ]
