# Generated by Django 6.0.5 on 2026-05-09 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.CharField(choices=[('T0', 'panic'), ('T1', 'slow'), ('T2', 'normal'), ('T3', 'high speed'), ('T4', 'aggressive'), ('T5', 'hyper aggressive')], max_length=100)),
                ('intensity', models.CharField(choices=[('N', 'normal'), ('M', 'medium'), ('H', 'high')], max_length=100)),
                ('short_note', models.CharField(max_length=75)),
                ('ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditor_panel.ippool')),
            ],
        ),
    ]
