# Generated by Django 6.0.5 on 2026-05-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor_panel', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippool',
            name='mask',
            field=models.GenericIPAddressField(default='255.255.255.0'),
            preserve_default=False,
        ),
    ]
