# Generated by Django 6.0.5 on 2026-07-23 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('subnet', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('ip_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanResult', to='main_page.iptable')),
            ],
        ),
    ]
